trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)
stages:
- stage: Build
  jobs:
  - job: 'Build'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo 'Hello world'
  - job: 'Test'
    dependsOn: 'Build'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
        architecture: 'x64'
- stage: Test
  jobs:
  - job: "Deploy"
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo 'Hello world '
  - job: "Prod"
    pool: server
    dependsOn: "Deploy"
    steps:
- task: InvokeRESTAPI@1
  inputs:
    connectionType: 'connectedServiceName'
    serviceConnection: 'E_Change_Control_Connection'
    method: 'POST'
    body: |
      {
      "buildNumber": "$(build.buildId)",
      "isMultiBranch": "true",
      "branchName": "$(build.sourceBranchName)"
      }
    waitForCompletion: 'true'
    - task: Delay@1
      inputs:
        delayForMinutes: '0'
