trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)
stages:
- stage: SingleStage
  jobs:
  - job: "Prod1"
    dependsOn: 'Deploy1'
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'E_Change_Control_Connection'
        method: 'POST'
        body: |
            {
              "buildNumber": "$(build.buildId)",
              "isMultiBranch": "true",
              "branchName": "$(build.sourceBranchName)"
            }
        waitForCompletion: 'true'
    - task: Delay@1
      inputs:
        delayForMinutes: '0'
  - job: "Deploy1"
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo 'Hello world ' 
- stage: Build
  jobs:
  - job: 'Build1'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo 'Hello world'
  - job: 'Test1'
    dependsOn: 'Build1'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
        architecture: 'x64'
