trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)
stages:
- stage: SingleStage
  jobs:
  - job: "Prod"
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'E_Change_Control_Connection'
        method: 'POST'
        waitForCompletion: 'true'
    - task: Delay@1
      inputs:
        delayForMinutes: '0'
